# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-03 11:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0002_auto_20160203_1125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='answer_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='answer.Answer'),
        ),
        migrations.AlterField(
            model_name='vote',
            name='question_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='question.Question'),
        ),
    ]
