# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-03 12:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userprofil', '0002_userprofile_user_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='user_name',
        ),
    ]
