# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-10 09:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofil', '0004_userprofile_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='email',
            field=models.EmailField(blank=True, max_length=70, null=True),
        ),
    ]
