# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-03 11:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='answer',
            field=models.ManyToManyField(blank=True, to='answer.Answer'),
        ),
    ]
