# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-10 15:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0003_question_question_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_comment',
            field=models.CharField(blank=True, max_length=200, verbose_name='comment.Comment'),
        ),
    ]
